spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_db
    username: xuan_nhi
    password: "123456"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

app:
  jwt:
    secret: minishop-super-secret-key-2024-xuan-nhi-shop-secret
    expiration: 86400000  # 24 hours in ms

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
